# Generated by Django 3.0.7 on 2020-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partes',
            options={'verbose_name': 'Partes del contrato', 'verbose_name_plural': 'Parte del contrato'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nombres_funcionario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='primerapellido_funcionario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='segundoapellido_funcionario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
