# Generated by Django 3.0.7 on 2020-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='current_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario actual'),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='docto16',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Documento 16'),
        ),
    ]
