# Generated by Django 3.0.7 on 2020-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0002_auto_20200622_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nombres_funcionario',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='primerapellido_funcionario',
            field=models.CharField(max_length=100, verbose_name='Primer apellido'),
        ),
    ]
