# Generated by Django 3.0.7 on 2020-07-09 22:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0002_auto_20200709_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='astep1',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Actividad step1'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='astep2',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Actividad step2'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='astep3',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Actividad step3'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='astep4',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Actividad step4'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='astep5',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Actividad step5'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='astep6',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Actividad step6'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='cstep1',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Comentarios 1'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='cstep2',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Comentarios 2'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='cstep3',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Comentarios 3'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='cstep4',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Comentarios 4'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='cstep5',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Comentarios 5'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='cstep6',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Comentarios 6'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='devuelto_por',
            field=models.IntegerField(blank=True, null=True, verbose_name='Devuelto por'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fcap',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Captura'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fstep1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha step1'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fstep2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha step2'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fstep3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha step3'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fstep4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha step4'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fstep5',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha step5'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fstep6',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha step6'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rcap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable de Captura'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rstep1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable step1'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rstep2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable step2'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rstep3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable step3'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rstep4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable step4'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rstep5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable step5'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rstep6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resposable step6'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='status',
            field=models.CharField(default='CAP', max_length=3, verbose_name='Status de la solicitud'),
        ),
    ]
