# Generated by Django 3.0.7 on 2020-07-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0003_auto_20200709_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctos',
            old_name='tipocontrato',
            new_name='contrato',
        ),
    ]
