# Generated by Django 3.2.9 on 2023-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0003_auto_20230313_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='objeto_social',
            field=models.TextField(default=''),
        ),
    ]
