# Generated by Django 3.0.7 on 2020-06-22 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cto', '0003_auto_20200622_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='partes',
            name='alergias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='partes',
            name='clave_depto',
            field=models.IntegerField(null=True, verbose_name='Clave de Depto.'),
        ),
        migrations.AddField(
            model_name='partes',
            name='codigo',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='partes',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='partes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='partes',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='partes',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='partes',
            name='imss',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='IMSS'),
        ),
        migrations.AddField(
            model_name='partes',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='partes',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='partes',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='partes',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partes',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
