# Generated by Django 3.2.9 on 2023-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0004_auto_20230313_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='domicilio_sociedad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contratos',
            name='registro_mercantil',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rfc_sociedad',
            field=models.CharField(default='', max_length=12),
        ),
    ]
