# Generated by Django 3.0.7 on 2020-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0004_auto_20200622_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes',
            name='alergias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='apellidoMaternoParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='apellidoPaternoParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='cedula_profParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cédula profesional'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='lugarnacimientoParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de nacimiento '),
        ),
        migrations.AlterField(
            model_name='partes',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Movil'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='nombresParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres del contratante'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='regfiscalParte',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Régimen fiscal '),
        ),
        migrations.AlterField(
            model_name='partes',
            name='tituloParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título '),
        ),
        migrations.AlterField(
            model_name='partes',
            name='titulo_profParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título profesional'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='universidadParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Universidad'),
        ),
    ]
