# Generated by Django 3.2.9 on 2023-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0005_auto_20230313_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='tipo_sociedad',
            field=models.CharField(default='Sociedad Anónima de Capital Variable', max_length=150),
        ),
    ]
