# Generated by Django 3.2.9 on 2023-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0006_contratos_tipo_sociedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='domicilio_sociedad',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='objeto_social',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='registro_mercantil',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='rfc_sociedad',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipo_sociedad',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
