# Generated by Django 3.0.7 on 2020-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0006_auto_20200624_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='parte1',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Parte 1'),
        ),
    ]
