# Generated by Django 3.0.7 on 2020-06-26 17:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0007_auto_20200624_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuencia',
            name='textoSecuencia',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto secuencia'),
        ),
    ]
